# Generated by Django 5.0.4 on 2025-04-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, default='', max_length=20)),
                ('card_number', models.CharField(blank=True, default='', max_length=255)),
                ('valid_till', models.CharField(blank=True, default='', max_length=255)),
                ('pin_number', models.CharField(blank=True, default='', max_length=255)),
                ('security_code', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='A', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(blank=True, default='', max_length=10)),
                ('account_number', models.CharField(blank=True, default='', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=10)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=255)),
                ('dob', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('city', models.CharField(blank=True, default='', max_length=150)),
                ('country', models.CharField(blank=True, default='', max_length=15)),
                ('postal_code', models.CharField(blank=True, default='', max_length=15)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='A', max_length=10)),
                ('ct', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.CharField(blank=True, default='', max_length=15)),
                ('ct', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_number', models.CharField(blank=True, default='', max_length=10)),
                ('frequency', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(blank=True, default='A', max_length=10)),
            ],
            options={
                'db_table': 'recurringPayment',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, default='', max_length=20)),
                ('transType', models.CharField(blank=True, default='', max_length=15)),
                ('amount', models.CharField(blank=True, default='', max_length=15)),
                ('summary', models.CharField(blank=True, default='', max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, default='', max_length=20)),
                ('requestType', models.CharField(blank=True, default='', max_length=15)),
                ('summary', models.CharField(blank=True, default='', max_length=250)),
                ('status', models.CharField(blank=True, default='O', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_requests',
            },
        ),
    ]
