# Generated by Django 5.0.4 on 2024-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
