# Generated by Django 5.0.4 on 2024-05-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customers_ct_alter_cards_date_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='pin_number',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='security_code',
        ),
    ]
