# Generated by Django 5.0.4 on 2024-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='account_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
