# Generated by Django 5.0.4 on 2024-05-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_customers_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.CharField(blank=True, default='', max_length=15)),
                ('ct', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_number', models.CharField(blank=True, default='', max_length=10)),
                ('frequency', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(blank=True, default='A', max_length=10)),
            ],
            options={
                'db_table': 'recurringPayment',
            },
        ),
    ]
