# Generated by Django 5.0.4 on 2024-05-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, default='', max_length=30)),
                ('valid_till', models.CharField(blank=True, default='', max_length=10)),
                ('pin_number', models.CharField(blank=True, default='', max_length=4)),
                ('security_code', models.CharField(blank=True, default='', max_length=3)),
                ('status', models.CharField(blank=True, default='A', max_length=10)),
                ('date', models.CharField(blank=True, default='', max_length=15)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customers')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
