# Generated by Django 5.0.4 on 2024-05-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_transaction_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance_after',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance_before',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='other_account_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='other_account_name',
        ),
    ]
