# Generated by Django 5.0.4 on 2024-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_cards_card_number_alter_cards_pin_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, default='', max_length=20)),
                ('requestType', models.CharField(blank=True, default='', max_length=15)),
                ('summary', models.CharField(blank=True, default='', max_length=250)),
                ('status', models.CharField(blank=True, default='O', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_requests',
            },
        ),
    ]
